name: test workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: ["12", "14", "15"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: yarn install --production false --frozen-lockfile

      - name: lint
        run: yarn run lint

#      - name: test
#        run: yarn run test:coverage
